server:
  port: 11111

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coj?useUnicode=true&characterEncoding=utf-8
    username: "xxx" # 替换为你的数据库用户名
    password: "xxx" # 替换为你的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    path match:
      matching-strategy: ant_path_matcher


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1

